main/urls.py
from django.urls import path

from main.views import Main, ProductionListView, ProductionDetails, TeamList, TeamMemberDetails, HeadLineDetailView, \
    AnnualReportsDetailView, NetworkPartnerDetailView, DonateSupportTemplateView, ContactUsTemplateView

app_name = 'main'

urlpatterns = [
    path('', Main.as_view(), name='main'),
    path('category/<str:slug>', ProductionListView.as_view(), name='sub_category_details'),
    path('category/', ProductionListView.as_view(), name='sub_category_details'),
    path('production/<str:slug>', ProductionDetails.as_view(), name='production_details'),
    path('team', TeamList.as_view(), name='team'),
    path('team/<str:slug>', TeamMemberDetails.as_view(), name='team_member'),
    path('headline/<str:slug>', HeadLineDetailView.as_view(), name='headline'),
    path('annual-reports', AnnualReportsDetailView.as_view(), name='annual_reports'),
    path('networks-&-partners', NetworkPartnerDetailView.as_view(), name='networks_and_partners'),
    path('donate-&-support', DonateSupportTemplateView.as_view(), name='donate_and_support'),
    path('contact-us', ContactUsTemplateView.as_view(), name='contact_us'),
]

theater/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from theater import settings

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n'))
]
urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layout/_coming_soon.html
{% load crispy_forms_tags i18n static %}
<div style="margin-top: 5rem"
     class="d-flex card p-3 {% if hide_coming_soon_page %}d-none{% endif %} container justify-content-center align-items-center flex-wrap flex-column ">
    <img class="bg-white img-fluid " width="110" src="{% static 'images/logo.png' %}">

    <svg style="margin-top: 2rem" class="loader" viewBox="0 0 100 100">
        <g class="points">
            <circle class="ciw" cx="50" cy="50" r="50" fill="#fff"/>
            <circle class="ci2" cx="5" cy="50" fill="#6d6e70" r="4"/>
            <circle class="ci1" cx="95" cy="50" fill="#b02a2f" r="4"/>
        </g>
    </svg>
    <h2 style="margin-top: 1rem" class="pt-2 font-bold text-dark-gray text-center text-uppercase">
        coming soon!
    </h2>
    <h2 dir="rtl" class="font-bold text-dark-red text-center text-uppercase">
        الموقع قيد التطوير...
    </h2>
</div>

templates/layout/_footer.html
{% load crispy_forms_tags i18n static %}

<footer class="wow fadeInUp mt-3 px-3 d-flex flex-wrap justify-content-between align-items-center py-3 border-top">
    <div class="col-md-4 d-flex align-items-center">
        <a href="/"
           class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
            <img width="40" height="50" href="{% url 'main:main' %}" src="{% static 'images/footer_logo.png' %}">
        </a>
        <a target="_blank" href="http://www.jomhour.ps/"
           class="text-dark">{% trans '© 2022 Provided by Jomhour.ps' %}</a>
    </div>

    <ul class="nav float-end col-md-4 justify-content-end list-unstyled d-flex">
        <li data-bs-toggle="tooltip" data-bs-placement="top" title="{% trans 'Twitter' %}" class="mx-2">
            <a class=" text-muted" href="#">
                <i class="fa footer-social-media fa-lg fa-twitter"></i>
            </a>
        </li>
        <li data-bs-toggle="tooltip" data-bs-placement="top" title="{% trans 'Instagram' %}" class="mx-2">
            <a class=" text-muted" href="#">
                <i class="fa footer-social-media fa-lg fa-instagram"></i>
            </a>
        </li>
        <li data-bs-toggle="tooltip" data-bs-placement="top" title="{% trans 'Facebook' %}" class="mx-2">
            <a class=" text-muted" href="#">
                <i class="fa footer-social-media fa-lg fa-facebook"></i>
            </a>
        </li>

        <li data-bs-toggle="tooltip" data-bs-placement="top" title="{% trans 'Youtube' %}" class="mx-2">
            <a class=" text-muted" href="#">
                <i class="fa footer-social-media fa-lg fa-youtube"></i>
            </a>
        </li>
    </ul>
</footer>

templates/layout/_header.html
{% load crispy_forms_tags i18n static main %}


<nav class="navbar navbar-expand-lg navbar-light pt-5 bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main:main' %}">
            <img width="70" height="100" src="{% static 'images/logo.png' %}"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 {% if activate_coming_soon %}d-none {% endif %} ">
                <li class="nav-item  me-auto ">
                    <a class=" font-bold text-dark-red nav-link" aria-current="page"
                       href="{% url 'main:main' %}">{% trans 'Home' %}</a>
                </li>
                <li class="nav-item  dropdown">
                    <a class="font-bold text-dark-red nav-link dropdown-toggle" href="#" id="navbarDropdown"
                       role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        {% trans 'Who we are' %}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for headline in headlines %}
                            <li>
                                <a class="p-3 dropdown-item" href="{{ headline.get_absolute_url }}">
                                    {{ headline.title }}
                                </a>
                            </li>
                        {% endfor %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="p-3 dropdown-item" href="{% url 'main:team' %}">{% trans 'Inad Team' %}</a></li>
                    </ul>
                </li>
                {% for category in categories %}
                    <li class="nav-item  dropdown">
                        <a class="font-bold text-dark-red nav-link dropdown-toggle" href="#" id="navbarDropdown"
                           role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            {{ category }}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% for sub_category in category.sub_categories.all %}
                                <li class="text-center">
                                    <a class="p-3 dropdown-item"
                                       href="{{ sub_category.get_absolute_url }}"
                                    >
                                        {{ sub_category }}
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endfor %}
                <li class="nav-item">
                    <a class="font-bold text-dark-red nav-link" aria-current="page"
                       href="{% url 'main:annual_reports' %}">  {% trans 'Annual Reports' %}</a>
                </li>
                <li class="nav-item">
                    <a class="font-bold text-dark-red nav-link" aria-current="page"
                       href="{% url 'main:networks_and_partners' %}">  {% trans 'Networks & Partners' %}</a>
                </li>
                <li class="nav-item">
                    <a class="font-bold text-dark-red nav-link" aria-current="page"
                       href="{% url 'main:donate_and_support' %}">  {% trans 'Donate & Support' %}</a>
                </li>
                <li class="nav-item">
                    <a class="font-bold text-dark-red nav-link" aria-current="page"
                       href="{% url 'main:contact_us' %}">  {% trans 'Contact Us' %}</a>
                </li>
            </ul>
            <div class="mx-2 dropdown">
                <button class="btn btn-outline-dark-red dropdown-toggle" type="button" id="dropdownMenuButton1"
                        data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-language me-1"></i> {{ lang.name_local }}
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    {% for language in languages %}
                        {% if language.code != CURRENT_LANGUAGE %}
                            <li class="p-2 text-center">
                                <a href="/{{ language.code }}/{{ request.get_full_path|slice:"4:" }}"
                                >
                                    {{ language.name_local }}

                                </a>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</nav>

templates/layout/_messages.html
<div id="messages">
    {% if messages %}
        {% for message in messages %}
            <div
                 class="alert {{ message.tags }} text-center alert-dismissible main-alert fade fadeInUp animate__fadeOut show">
                <strong>{{ message }}</strong>
            </div>
        {% endfor %}
    {% endif %}
</div>

templates/layout/base.html
{% load static i18n compress %}

{% get_language_info_list for available_languages as languages %}
{% get_current_language as CURRENT_LANGUAGE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% get_language_info for CURRENT_LANGUAGE as lang %}

<!DOCTYPE html>
<html lang="{{ CURRENT_LANGUAGE|default:"en" }}"
      {% if LANGUAGE_BIDI %}dir="rtl" {% else %}dir="ltr"{% endif %}
      style="overflow-x: hidden;">
<head>
    <meta charset="utf-8">
    <meta name="description" content="{% trans "Inad Theater" %}|{% block site_description %}{% endblock %}">
    <meta property="og:url" content="{{ request.build_absolute_uri }}">
    <meta name="author" content="{% trans "Inad Theater" %}">
    <meta name="keywords" content="{% block keywords %}{% endblock %}"/>
    <meta property="og:locale" content="en_GB">
    <meta property="og:locale:alternate" content="ar_AR"/>
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="Inad Theater">
    <meta property="og:image:width" content="300">
    <meta property="og:image:height" content="300">
    <meta property="og:image" itemprop="image" content="{% block og_image %}{% endblock %} ">
    <meta property="og:image:alt" itemprop="image" content="Inad Theater">
    <link rel='image_src' href='{% static '' %}'/>
    <meta name="version" content="1.0.0">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/logo.png' %}"/>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="HandheldFriendly" content="true">
    <title>{% trans "Inad Theater" %} | {% block site_title %}{% endblock %}</title>
    <meta property="og:title" content="{% trans "Inad Theater" %} | {% block site_og_title %}{% endblock %}">
    <meta property="og:description"
          content="{% trans "Inad Theater" %} | {% block site_og_description %}{% endblock %}">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:creator" content="@inadtheater">
    <meta name="twitter:site" content="@inadtheater">
    <meta name="twitter:label1" content="Inad Theater">
    <meta name="twitter:data1" content="Inad Theater">
    <meta name="twitter:label2" content=" {% trans "Estimated reading time" %}: {% block reading_time %}{% endblock %}">
    <meta name="twitter:data2" content="2 Minutes">
    <link rel="canonical" href="{% block canonical %}{% endblock %}">
    <meta name="robots" content="noodp,noydir"/>
    <link rel="shortcut icon" href="{% static 'images/logo.png' %}" type="image/x-icon">
    <!-- Favicons -->
    <link href="{% static 'images/logo.png' %}" rel="icon">
    <link href="{% static 'images/logo.png' %}" rel="apple-touch-icon">



    {% compress css %}
        <link rel="stylesheet" href="{% static 'vendor/css/bootstrap.min.css' %}">
        <link href="{% static 'vendor/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
        <link href="{% static 'vendor/owlcarousel/assets/owl.theme.default.min.css' %}" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'vendor/fonts/Changa/font.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/fonts/Roboto_Condensed/font.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link href="{% static 'vendor/animate/animate.min.css' %}" rel="stylesheet">

        {% block app_css %}
        {% endblock %}
    {% endcompress %}

</head>
<body>
{% block base_content %}
{% endblock %}
<script src="https://kit.fontawesome.com/1c39875901.js" crossorigin="anonymous"></script>

{% compress js %}
    <script src="{% static 'vendor/js/popper.min.js' %}"></script>
    <script src="{% static 'vendor/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/js/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/wow/wow.min.js' %}"></script>
    <script src="{% static 'vendor/owlcarousel/owl.carousel.min.js' %}"></script>
    <script defer src="{% static 'js/scripts.js' %}"></script>

{% endcompress %}
{% block app_js %}
{% endblock %}
</body>
</html>

templates/layout/layout.html
{% extends "layout/base.html" %}
{% load static %}
{% load i18n %}

{% block base_content %}

    {% if activate_coming_soon %}
        {% include "layout/_coming_soon.html" %}
    {% endif %}
    {% if hide_coming_soon_page %}
        <div>
            {% if not activate_coming_soon %}
                {% include "layout/_header.html" %}
            {% endif %}

            <div class="mb-0 container main-wrapper">
                {% if activate_coming_soon %}
                    <nav class="navbar d-none  navbar-light bg-light">
                        <form action="{% url 'main:sub_category_details' %}" class="d-flex container-fluid">
                            <div class="p-2 me-3 input-group">
                                <button id="buttonSubmit" value="submit" class="input-group-text"><i
                                        class="fa  text-dark-red fa-search"></i></button>
                                <input class="form-control p-2 " name="search" type="search"
                                       placeholder="{% trans 'Search' %}"
                                       aria-label="Search">

                            </div>
                        </form>
                    </nav>
                {% endif %}
                {% include "layout/_messages.html" %}
                <div class="main-content-wrapper container-fluid">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
            <div id='toTop'><i class="fa fa-2x text-dark-red btn fa-arrow-circle-o-up"></i></div>
            {% if not activate_coming_soon %}
                {% include "layout/_footer.html" %}
            {% endif %}

        </div>
    {% endif %}
{% endblock %}